apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
   release: stable
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfsroot
    server: 192.168.43.33
