apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  labels:
    app: flask-app
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: flask
